# Generated by Django 5.0.14 on 2025-06-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongViec',
            fields=[
                ('id_cong_viec', models.AutoField(primary_key=True, serialize=False)),
                ('ten_cong_viec', models.CharField(max_length=35)),
                ('luong_toi_thieu', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('luong_toi_da', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'cong_viec',
            },
        ),
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id_dia_diem', models.AutoField(primary_key=True, serialize=False)),
                ('dia_chi_duong', models.CharField(max_length=40, null=True)),
                ('ma_buu_dien', models.CharField(max_length=12, null=True)),
                ('thanh_pho', models.CharField(max_length=30)),
                ('tinh_thanh', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'dia_diem',
            },
        ),
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('id_khu_vuc', models.AutoField(primary_key=True, serialize=False)),
                ('ten_khu_vuc', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'khu_vuc',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id_nhan_vien', models.AutoField(primary_key=True, serialize=False)),
                ('ho', models.CharField(max_length=30)),
                ('ten', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('so_dien_thoai', models.CharField(max_length=20, null=True)),
                ('ngay_thue', models.DateField()),
                ('luong', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_cong_viec', models.ForeignKey(db_column='id_cong_viec', on_delete=django.db.models.deletion.CASCADE, to='main.congviec')),
                ('id_quan_ly', models.ForeignKey(blank=True, db_column='id_quan_ly', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.nhanvien')),
            ],
            options={
                'db_table': 'nhan_vien',
            },
        ),
        migrations.CreateModel(
            name='NguoiPhuThuoc',
            fields=[
                ('id_nguoi_phu_thuoc', models.AutoField(primary_key=True, serialize=False)),
                ('ho', models.CharField(max_length=30)),
                ('ten', models.CharField(max_length=20)),
                ('quan_he', models.CharField(max_length=25)),
                ('id_nhan_vien', models.ForeignKey(db_column='id_nhan_vien', on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien')),
            ],
            options={
                'db_table': 'nguoi_phu_thuoc',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id_phong_ban', models.AutoField(primary_key=True, serialize=False)),
                ('ten_phong_ban', models.CharField(max_length=30)),
                ('id_dia_diem', models.ForeignKey(db_column='id_dia_diem', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diadiem')),
            ],
            options={
                'db_table': 'phong_ban',
            },
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='id_phong_ban',
            field=models.ForeignKey(db_column='id_phong_ban', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.phongban'),
        ),
        migrations.CreateModel(
            name='QuocGia',
            fields=[
                ('id_quoc_gia', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('ten_quoc_gia', models.CharField(max_length=40, null=True)),
                ('id_khu_vuc', models.ForeignKey(db_column='id_khu_vuc', on_delete=django.db.models.deletion.CASCADE, to='main.khuvuc')),
            ],
            options={
                'db_table': 'quoc_gia',
            },
        ),
        migrations.AddField(
            model_name='diadiem',
            name='id_quoc_gia',
            field=models.ForeignKey(db_column='id_quoc_gia', on_delete=django.db.models.deletion.CASCADE, to='main.quocgia'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lam', models.DateField(auto_now_add=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('gio_lam', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ngay_cong', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('id_nhan_vien', models.ForeignKey(db_column='id_nhan_vien', on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-ngay_lam'],
                'unique_together': {('id_nhan_vien', 'ngay_lam')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.DateField()),
                ('tong_ngay_lam', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('luong_thuc_nhan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ngay_tinh', models.DateTimeField(auto_now_add=True)),
                ('id_nhan_vien', models.ForeignKey(db_column='id_nhan_vien', on_delete=django.db.models.deletion.CASCADE, to='main.nhanvien')),
            ],
            options={
                'db_table': 'payrollrecord',
                'ordering': ['-thang'],
                'unique_together': {('id_nhan_vien', 'thang')},
            },
        ),
    ]
